services:

  codekata.application.application:
    class: "\CodeKata\RomanNumerals\Application\Application"
    arguments:
      - "@codekata.application.symfony-console-application"
      - "@codekata.application.hello-command"

  codekata.application.hello-command:
    class: "\CodeKata\RomanNumerals\Application\HelloCommand"
    arguments:
      - "@codekata.domain.hello-service"

  codekata.application.symfony-console-application:
    class: "\Symfony\Component\Console\Application"
